server:
  port: 8082
spring:
  application:
    name: order
  jpa:
    show-sql: true
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://192.168.205.136:3306/firstDB
    username: ldh
    password: ldh
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/

