
server:
  port: 8761
#设置服务名称
spring:
  application:
    name: eureka-server
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8761/eureka/
    register-with-eureka: false  #注册中心服务不显示在列表中

